### ISSUE TITLE
view moves using left and right arrow keys

### ISSUE THREAD

**Issue by moonpatel** [moonpatel/ChessHub#13]
Add a feature to view the previous and next moves using left and right arrow keys.

**Comment by Soumya-RanjanSwain** [comment]
Can you assign this to me I can work on it @moonpatel

**Comment by Parthasarathip123** [comment]
I would like to work on this issue can you please assign me @moonpatel

**Comment by moonpatel** [comment]
> Can you assign this to me I can work on it @moonpatel

Go ahead @DEV-Soumya-Ranjan-Swain. I have assigned the issue to you.

**Comment by moonpatel** [comment]
> I would like to work on this issue can you please assign me @moonpatel

@Parthasarathip123 I have assigned issue #12 to you.

**Comment by moonpatel** [comment]
Are you still working on this @DEV-Soumya-Ranjan-Swain ?

**Comment by Soumya-RanjanSwain** [comment]
Actually I tried searching for some functions in the the stockfish engine but I couldn't find something that keep tracks of it. If you can give some idea, I can complete it.

**Comment by moonpatel** [comment]
> Actually I tried searching for some functions in the the stockfish engine but I couldn't find something that keep tracks of it. If you can give some idea, I can complete it. 

@DEV-Soumya-Ranjan-Swain 
You should have asked it sooner. See for this issue you just have to attach a listener to the left and right keys and inside that listener call the goBack() and goAhead() functions inside the chess-game-context.jsx accordingly. Hope that helps. Feel free to ping if you have any other queries.

**Comment by Soumya-RanjanSwain** [comment]
@moonpatel can you check the above pr

**Comment by Soumya-RanjanSwain** [comment]
is there any conflict in merging @moonpatel ?

**Comment by moonpatel** [comment]
Use import.meta.env.VITE_BACKEND_HOST in Authentication.jsx file. This value comes from the .env file in frontend dir. It is easy to manage .env variables in case the backend is hosted on cloud.
@DEV-Soumya-Ranjan-Swain

**Comment by Soumya-RanjanSwain** [comment]
i have done the changes, you can merge it now
