### ISSUE TITLE
mark the last move made

### ISSUE THREAD

**Issue by moonpatel** [moonpatel/ChessHub#24]
Mark the last move made on the chess board.
![image](https://github.com/moonpatel/ChessHub/assets/95487062/d339973d-ce8f-492d-a048-9c56259e47d6)

**Comment by eugeneanokye99** [comment]
can you please assign me

**Comment by moonpatel** [comment]
sure go ahead @eugeneanokye99

**Comment by blacksag** [comment]
Hey @moonpatel, @eugeneanokye99, not sure if you are still working on this. I have created a PR for the same with the required changes, see if this works.
